version: '3'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./config/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml