version: '3'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    hostname: clickhouse-01
    container_name: clickhouse-01
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./config/config.d/custom-config.xml:/etc/clickhouse-server/config.d/custom-config.xml
      - ./config/users.d/demouser.xml:/etc/clickhouse-server/users.d/demouser.xml